services: 
  mediamtx: 
    image: bluenviron/mediamtx:latest 
    container_name: mediamtx 
    network_mode: host 
    volumes: 
      - ./mediamtx.yml:/mediamtx.yml 
      - ./recordings:/recordings
    restart: unless-stopped
