services:
  generate:
    build: .
    container_name: planetiler-china-latest
    volumes:
      - ./:/data
    environment:
      - JAVA_OPTS=-Xmx24g
    command: >
      --osm-path=china-latest.osm.pbf
      --output=china-latest.pmtiles
      --area=china
      --max-zoom=19
      --threads=8
      --download
      --verbose
      --force
    deploy:
      resources:
        limits:
          memory: 28G