version = "0.2"

[[tasks]]
  key = "CleanLogs"
  title = "清理操作日志"
  description = "每天凌晨 2 点清理日志，仅保留最近 3 个月数据"
  cron = "0 0 2 * * *"
  [tasks.func]
    name = "CleanLogs" # 函数名
    expired = "2160h"
[[tasks]]
  key = "CleanDeviceLogs"
  title = "清理设备日志"
  description = "每天凌晨 2 点清理设备日志，仅保留最近 3 个月数据"
  cron = "0 1 2 * * *"
  [tasks.func]
    name = "CleanDeviceLogs"
    expired = "2160h"
[[tasks]]
  key = "CleanVcode"
  title = "清理验证码"
  description = "每天凌晨 2 点清理验证码，仅保留最近 1 个月数据"
  cron = "0 2 2 * * *"
  [tasks.func]
    name = "CleanVcode"
    expired = "720h"
[[tasks]]
  key = "CleanAlarm"
  title = "清理报警"
  description = "每小时正点清理报警事件，仅保留最近 1 个月数据"
  cron = "0 0 * * * *"
  [tasks.func]
    name = "CleanAlarm"
    expired = "720h"